name: Merge Main into Pages

on:
  workflow_dispatch:

jobs:
  merge-main-into-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout the pages branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch }} # Checkout the pages branch

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Show git status
        run: git status

      - name: Fetch latest changes from the main branch
        run: git fetch origin main

      - name: Merge main into pages
        run: |
          git merge origin/main --no-ff -m "Merging main into pages" || git merge origin/main --strategy=recursive -X theirs

      - name: Push changes to the pages branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }} # Push changes to pages branch
