name: CI

on:
  workflow_dispatch:
    inputs:
      song:
        description: 'Input url Song spotify'
        required: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Extract Branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Set up Python latest version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Depedenciest npm
        run: |
          npm install
      - name: Install spotdl
        run: |
          pip install -U yt-dlp spotdl
      - name: Download spotdl meta
        run: |
          spotdl save ${{ github.event.inputs.song }} --save-file ./spotdl_data/data.spotdl
      - name: Download spotdl music with retry
        run: |
          set +e
          for i in {1..3}; do
            spotdl ${{ github.event.inputs.song }} --output ./music
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Retrying download ($i/3)..."
            sleep 10
          done
          set -e
      - name: Running app
        run: |
          node app.js
      - name: Commit
        run: |
          git config --local user.name "mrtampan"
          git config --local user.email "mrtampan@gmail.com"
          git add -A
          git commit -m "[AUTO:BUILD] build from musiclist.json"
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
